### ISSUE TITLE
Test velocity exchanges across the tripolar seam more thoroughly

### ISSUE THREAD

**Issue by NoraLoose** [CliMA/Oceananigans.jl#4488]
The failing test in [#4487](https://github.com/CliMA/Oceananigans.jl/pull/4487) suggests that velocity exchanges across the tripolar seam may not be handled correctly. Regardless of whether this is the root cause, it would be valuable to add a more robust unit test to explicitly verify exchange behavior.

I propose extending [this testset](https://github.com/CliMA/Oceananigans.jl/blob/af4a68a579f98268b3406540233504ccabdfc68b/test/test_tripolar_grid.jl#L165) with a test that:

- Initializes `u` and `v` from a random streamfunction.
- Applies velocity exchanges across the seam ( I think via `fill_halo_regions!`?).
- Applies the exchanges a second time.
- Verifies that the initial velocity fields coincide with the velocity fields after the second exchange.

**Comment by glwagner** [comment]
I 100% support this new test! On where to put it: I think its nice to sort the tests into more unit-style tests which just test a boundary condition, versus integration tests that bring lots of things together. I'm not sure the best place for an actual tripolar grid simulation --- possibly within the hydrostatic model tests?

**Comment by NoraLoose** [comment]
I think such a test would fit nicely into this testset:

https://github.com/CliMA/Oceananigans.jl/blob/af4a68a579f98268b3406540233504ccabdfc68b/test/test_tripolar_grid.jl#L165

We don't need to run any simulation for this test, it just tests the zipper boundary condition including its exchanges.

**Comment by glwagner** [comment]
I think that `v` should change signs too right? At least that would make sense to me

**Comment by glwagner** [comment]
Maybe we should add the "Gaussian mountains" bathymetry to the source code seeing as it is pretty useful for development...

**Comment by glwagner** [comment]
I just noticed the streamfunction is at the wrong location (should be Face, Face, Center) but I don't know if that affects the reuslts... trying to run myself too

**Comment by NoraLoose** [comment]
Yes, I think you are right -- `v` should change signs too.

**Comment by glwagner** [comment]
```julia> v.boundary_conditions.north
ZipperBoundaryCondition: -1

julia> u.boundary_conditions.north
ZipperBoundaryCondition: -1
```

this looks right so it might be in the halo filling

**Comment by glwagner** [comment]
Okay so maybe I don't totally understand TripolarGrid --- working on it!

Here's the halo filling for `u`:

https://github.com/CliMA/Oceananigans.jl/blob/235cee572e08e269d77900cd9dd73d0a27ad1801/src/BoundaryConditions/fill_halo_regions_zipper.jl#L65-L81

The last few lines ensure consistency by enforcing the notion that half of the top row is redundant.

But we don't do the same for `v`:

https://github.com/CliMA/Oceananigans.jl/blob/235cee572e08e269d77900cd9dd73d0a27ad1801/src/BoundaryConditions/fill_halo_regions_zipper.jl#L83-L96

**Comment by glwagner** [comment]
Ok, so I guess to see `v` we actually have to look into the halos, right? Because the interior cells for `v` will not have a sign flip

**Comment by NoraLoose** [comment]
My understanding is that consistency for `v` would look like this:

* The last interior row of `v` on the right side should equal the negative of the second-to-last interior row of `v` on the left side.
* The second-to-last interior row of `v` on the right side should equal the negative of the last interior row of `v` on the left side.

That would be consistent with a pivot point placed at a u-point.

**Comment by glwagner** [comment]
By "interior" do you mean the face at Ny+1 (eg pointing out of the grid) or the face at Ny ?

**Comment by NoraLoose** [comment]
<img width="349" alt="Image" src="https://github.com/user-attachments/assets/a90b5043-c81e-48e8-8196-c2230d9fc06d" />

**Comment by glwagner** [comment]
ok right! this makes sense

**Comment by glwagner** [comment]
Yeah so something is wrong

**Comment by NoraLoose** [comment]
Unless the pivot point is not placed in tracer row Ny? We need @simone-silvestri !

**Comment by glwagner** [comment]
> My understanding is that consistency for `v` would look like this:
> 
> * The last interior row of `v` on the right side should equal the negative of the second-to-last interior row of `v` on the left side.
> * The second-to-last interior row of `v` on the right side should equal the negative of the last interior row of `v` on the left side.
> 
> That would be consistent with a pivot point placed at a u-point.

Ok, the first point is accomplished here: 

https://github.com/CliMA/Oceananigans.jl/blob/235cee572e08e269d77900cd9dd73d0a27ad1801/src/BoundaryConditions/fill_halo_regions_zipper.jl#L91

for example plugging in `j=1` (which is a bad idex to use, since this is not the normal meaning of `j`!), we get

```julia
v[i, Ny+1, k] = - v[ip, Ny, k]
```

where `i` runs upwards and `ip` runs downwards. I think the left side is taken as truth here.

We are missing the second part though.

Also the filling for vorticity is wrong, I think, but I am not sure where that is used.

**Comment by glwagner** [comment]
@NoraLoose see if this looks right: https://github.com/CliMA/Oceananigans.jl/pull/4487/commits/e118e8294df09334ca20ba7dccae3c09bd34d9fe

**Comment by glwagner** [comment]
Vorticity is also missing something similar: 

https://github.com/CliMA/Oceananigans.jl/blob/235cee572e08e269d77900cd9dd73d0a27ad1801/src/BoundaryConditions/fill_halo_regions_zipper.jl#L49-L63

**Comment by glwagner** [comment]
Hmm, I think the rule for vorticity is the same as for `v` (because they are on the same north-south level)

**Comment by simone-silvestri** [comment]
> <img alt="Image" width="349" src="https://private-user-images.githubusercontent.com/23617395/441872976-a90b5043-c81e-48e8-8196-c2230d9fc06d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY3NzMxMjgsIm5iZiI6MTc0Njc3MjgyOCwicGF0aCI6Ii8yMzYxNzM5NS80NDE4NzI5NzYtYTkwYjUwNDMtYzgxZS00OGU4LTgxOTYtYzIyMzBkOWZjMDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTA5VDA2NDAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNjE2YzI1OWIzZjNmNzExZWMyZWVmYmY5MWI4ZDZkZjhkZGYyYzczYmU3Y2ExYmEwMzI3Njc3MTk5NTQ5NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R5JzoPtMfRI8JgfAbtfxJuFWEUHDQh5agW1JL20fxr8">

This is how the seam is implemented. So tracer row `Ny` is split in two by the pole and `c[1:Nx÷2, Ny, :] == c[Nx:-1:Nx÷2+1, Ny, :]`

How can we test that the BC are correct?

**Comment by simone-silvestri** [comment]
> [@NoraLoose](https://github.com/NoraLoose) see if this looks right: [e118e82](https://github.com/CliMA/Oceananigans.jl/commit/e118e8294df09334ca20ba7dccae3c09bd34d9fe)

I guess this was not implemented because `YFaceField`s end at the `Ny` row so just below the pole and their value is not repeated. Maybe this implementation leads to flaws?

**Comment by simone-silvestri** [comment]
Probably something to check is that the areas of a `TripolarGrid` (`Azᶜᶜᶜ`) minus the redundant half row, sum to `4π`. If not we might have conservation issues

**Comment by simone-silvestri** [comment]
```
julia> grid = TripolarGrid(size = (20, 20, 1), z = (0, 1), southernmost_latitude=-89.999999999999, radius=1)
20×20×1 OrthogonalSphericalShellGrid{Float64, Periodic, Oceananigans.Grids.RightConnected, Bounded} on CPU with 4×4×4 halo and with precomputed metrics
├── centered at (λ, φ) = (70.0, -2.7141)
├── longitude: Periodic  extent 360.048 degrees                        variably spaced with min(Δλ)=3.12853e-13, max(Δλ)=18.9263
├── latitude:  Oceananigans.Grids.RightConnected  extent 189.0 degrees variably spaced with min(Δφ)=1.11249, max(Δφ)=9.47368
└── z:         Bounded  z ∈ [0.0, 1.0]                                 regularly spaced with Δz=1.0

julia> (sum(grid.Azᶜᶜᵃ[1:20, 1:20]) - sum(grid.Azᶜᶜᵃ[:, 20]) / 2) / π
4.003256656518659
```
Looks like the area is indeed a bit too large.

**Comment by NoraLoose** [comment]
> Hmm, I think the rule for vorticity is the same as for v (because they are on the same north-south level)

Why do we need an exchange rule for vorticity? Do we have any **prognostic** variables sitting at vorticity points?

**Comment by NoraLoose** [comment]
> How can we test that the BC are correct? There are some BC tests but maybe they are not enough?

A useful improvement would be to initialize tracers and velocity fields with random values instead of spatially constant ones (here 1's). 

https://github.com/CliMA/Oceananigans.jl/blob/235cee572e08e269d77900cd9dd73d0a27ad1801/test/test_tripolar_grid.jl#L196-L200

This approach would introduce variability that makes it easier to detect errors in boundary exchanges and mirroring logic.

https://github.com/CliMA/Oceananigans.jl/blob/235cee572e08e269d77900cd9dd73d0a27ad1801/test/test_tripolar_grid.jl#L211-L213

**Comment by NoraLoose** [comment]
The tracer conservation test in https://github.com/CliMA/Oceananigans.jl/pull/4487 is still failing, so we need more fixes beyond [e118e82](https://github.com/CliMA/Oceananigans.jl/commit/e118e8294df09334ca20ba7dccae3c09bd34d9fe).

**Comment by simone-silvestri** [comment]
However the ffa areas seem to be correct, which means that the tessellation is done on nodes?
```
julia> grid = TripolarGrid(size = (20, 20, 1), z = (0, 1), southernmost_latitude=-89.9999999999999, radius=1)
20×20×1 OrthogonalSphericalShellGrid{Float64, Periodic, Oceananigans.Grids.RightConnected, Bounded} on CPU with 4×4×4 halo and with precomputed metrics
├── centered at (λ, φ) = (70.0, -2.7141)
├── longitude: Periodic  extent 360.048 degrees                        variably spaced with min(Δλ)=3.30766e-14, max(Δλ)=18.9263
├── latitude:  Oceananigans.Grids.RightConnected  extent 189.0 degrees variably spaced with min(Δφ)=1.11249, max(Δφ)=9.47368
└── z:         Bounded  z ∈ [0.0, 1.0]                                 regularly spaced with Δz=1.0

julia> sum(grid.Azᶠᶠᵃ[1:20, 1:20]) / π
3.9999999999999987

julia> sum(grid.Azᶜᶠᵃ[1:20, 1:20]) / π
3.9956498596893164
```

**Comment by glwagner** [comment]
Is there a precision issue during construction of the grid?

**Comment by simone-silvestri** [comment]
Hmm, I am not sure. It looks like `grid.Azᶠᶠᵃ` tessellates the sphere quite precisely, so maybe there is a mismatch between `Azᶠᶠᵃ` and the other grid areas

**Comment by simone-silvestri** [comment]
After #4546 we can test the conservation of a tracer on the tripolar grid much more easily.
On #4546 I could verify that the problem with the tripolar grid is not necessarily not conserving tracer but not conserving volume. 
This is easily testable by evolving a uniform tracer. What happens is that the tracer remains uniform but the integral changes which means that volume has changed in the evolution.

**Comment by glwagner** [comment]
Is this still an issue?

**Comment by simone-silvestri** [comment]
I am not sure. I know that conservation down to 1e-16 is very difficult and there are compounding precision errors that destroy conservation up to 1e-12 for certain cases, maybe this was one of them?

**Comment by glwagner** [comment]
Can we either address this issue or close it?

**Comment by NoraLoose** [comment]
This may pose a problem for users who want to run Oceananigans on a tripolar grid for marine carbon dioxide removal (mCDR) experiments. In mCDR studies, two simulations are typically performed: a counterfactual (control) run and an intervention run, and the tracer response is diagnosed from their difference. Because this tracer difference diffuses rapidly, you need double-precision output to detect it reliably. Tracer conservation to machine precision is therefore critical for these applications.

Did we ever track down why we have tracer conservation up to machine precision on the lat-lon grid, but not on the tripolar grid?

**Comment by simone-silvestri** [comment]
if someone has some time on their hands it would be nice to address this issue. 
For sure #4811 will change stuff significantly, i.e., AB2 is not conservative anymore.
I have noticed, for example, that using BigFloat instead of Float64 the difference changes from 1e-13 to 1e-75, which clearly indicates the presence of numerical precision issues.

**Comment by glwagner** [comment]
> I have noticed, for example, that using BigFloat instead of Float64 the difference changes from 1e-13 to 1e-75, which clearly indicates the presence of numerical precision issues.

where do you use BigFloat and how?

> For sure https://github.com/CliMA/Oceananigans.jl/pull/4811 will change stuff significantly, i.e., AB2 is not conservative anymore.

How should investigation proceed then?

**Comment by simone-silvestri** [comment]
RK3 should be conservative. I think it might be enough to check the conservation in simpler simulations. For example, I am seeing these numerical errors popping up in https://github.com/CliMA/Oceananigans.jl/blob/main/validation/z_star_coordinate/lock_release.jl. By changing the default floating point precision, the error on the conservation will change, it is additive (meaning that unfortunately it grows), but related to the underlying precision, i.e. for a single precision run the error in the simulation is about 1e-5, for a double precision about 1e-12 and for BigFloat it goes down to 1e-75.

**Comment by glwagner** [comment]
What exactly does "conservation to machine precision" mean then? Does it mean that the error is Nt * Nx * Ny * Nz * eps(FT)? What should we expect to find? What is eps for BigFloat?

**Comment by simone-silvestri** [comment]
I am not sure, I think for my purposes a conservation of `100*eps` or even `1000*eps` is ok unless we want to use single precision. But for @NoraLoose's purposes it seem to be not enough. In terms of eps, for a BigFloat we have 1e-77.

**Comment by NoraLoose** [comment]
> What exactly does "conservation to machine precision" mean then? Does it mean that the error is Nt * Nx * Ny * Nz * eps(FT)? What should we expect to find? 

I think we should expect this test to pass (it does for all grid types except tripolar):

https://github.com/CliMA/Oceananigans.jl/blob/bd7b6476cf70a66743b340014ad2ed07718dd887/test/test_zstar_coordinate.jl#L9-L57

Isn't it a problem if the error grows proportional to `Nt`? That's not what I would expect. (Not saying that @simone-silvestri should fix it, I'm just trying to understand the source of the problem. :))

**Comment by glwagner** [comment]
If there is a conservation error at each time-step, shouldn't it accumulate in time?

If the errors are random, then there could be cancellations. So it would only be ~ Nt in the worst case.

The above tests use `isapprox`, which uses rtol of sqrt(eps(FT))

**Comment by glwagner** [comment]
> I am not sure, I think for my purposes a conservation of `100*eps` or even `1000*eps` is ok unless we want to use single precision. But for [@NoraLoose](https://github.com/NoraLoose)'s purposes it seem to be not enough. In terms of eps, for a BigFloat we have 1e-77.

In your results, Float64 has the biggest error relative to eps --- 1e4 * eps(FT). Single precision has 1e3 * eps(FT), and BigFloat has 100 * eps(FT). Is that correct interpretation of what you have written?

**Comment by simone-silvestri** [comment]
hmm, I guess then it is still an issue. `sqrt(eps(FT))` is quite large so I am not expecting conservation to break that much.
I should redo the test to see what is the error in that case, I might be remembering in an improper way 😅 .

**Comment by glwagner** [comment]
Note for comparisons with relative tolerances, it matters whether `∫b` and `∫c` are near 0 or not. It is probably best to ensure that their integrals are something regular (like 1 for ∫c)

**Comment by simone-silvestri** [comment]
I just checked again and on the TripolarGrid the error is indeed about 1e-7 for both `b` and `c`, even for non-zero integrals. It definitely is a tripolar grid issue then.

**Comment by glwagner** [comment]
The relative or absolute error is 1e-7? Is that for Float64? How big are the integrals?

**Comment by simone-silvestri** [comment]
the relative error is 1e-7 with the integrals in the order of 1e16 for Float64

**Comment by glwagner** [comment]
Okay, and the test with `isapprox` and default tolerance fails because

```julia
julia> sqrt(eps(Float64))
1.4901161193847656e-8
```

My questions are:

1. What tolerance is appropriate here? `sqrt(eps(FT))` is a convenient heuristic but it is not specific to this particular test. I think we should choose the acceptable tolerance intentionally.

2. If the machine precision errors are random and have zero mean then there should not be accumulation that depends on the duration of the simulation or problem size. But I am not sure we have that? Should we expect that?

It might be useful to look at the distribution of errors that develop when advecting a tracer `c=1` everywhere?

**Comment by simone-silvestri** [comment]
I just discovered that the error is not connected to actual conservation on the tripolar grid, but how we compute the averages. 
The last line is repeated so we should include only half of it on the reductions.

@NoraLoose you can test that conservation actually works when using 
```julia
using KernelAbstractions: @kernel, @index

@kernel function _subtract_line!(∫f, grid, f)
    i, k = @index(Global, NTuple)
    j = size(grid, 2)

    immersed = Oceananigans.ImmersedBoundaries.immersed_cell(i, j, k, grid)

    if !immersed
        ∫f[] -= f[i, j, k] 
    end
end

function my_average(field)
    f_V = field * Oceananigans.Operators.volume
    ∫f_V = Ref(sum(f_V))
    V = KernelFunctionOperation{Oceananigans.Fields.location(field)...}(Oceananigans.Operators.Vᶜᶜᶜ, field.grid)
    ∫V = Ref(sum(V))
    
    Nx, Ny, Nz = size(field.grid)
    params = KernelParameters(Nx÷2+1:Nx, 1:Nz)
    
    launch!(CPU(), field.grid, params, _subtract_line!, ∫f_V, field.grid, f_V)
    launch!(CPU(), field.grid, params, _subtract_line!, ∫V,   field.grid, V)
    
    return ∫f_V[] / ∫V[]
end 
```
I have implemented a correction in a branch that introduces this condition through a `ConditionalOperation` (similarly to what we do with immersed fields) that should close this issue. I verified that conservation is correct, but will open a PR only after #4811 (I started from that branch since it changes a bunch of zstar stuff).

@NoraLoose I will add to that branch the tests you have in #4487 if it is not a problem.

**Comment by glwagner** [comment]
Can you open the PR @simone-silvestri so we can see the code? Open the PR so that it points towards the branch in #4487.

**Comment by NoraLoose** [comment]
@simone-silvestri nice work finding the cause of the problem!

**Comment by simone-silvestri** [comment]
> Can you open the PR [@simone-silvestri](https://github.com/simone-silvestri) so we can see the code? Open the PR so that it points towards the branch in [#4487](https://github.com/CliMA/Oceananigans.jl/pull/4487).

I have opened #5099, but not 100% sure it will work before #4811 (it is working within that framework)
